### ISSUE TITLE
Inference Code

### ISSUE THREAD

**Issue by TheMattBin** [balabooooo/AED#3]
Thanks for the great work! I check the inference code but it seems only for test datasets, may I know where I can make use the inference script for own video?

**Comment by balabooooo** [comment]
@TheMattBin 
Thanks for your interest in our work！

You're right, our code currently supports some specific test datasets only.
Since I am currently maintaining this repository alone, it will take some time to update the feature that supports any video.
If you are in a hurry, I can give you some suggestions.
You can use a detector along with the video you want to replace the dataset (i.e. ListImgDataset class) in the inference stage.

If you have any other questions, feel free to discuss them with me.

**Comment by TheMattBin** [comment]
Thanks for the quick response! I will take a look at that!
